import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  button: {
    fontSize: 25,
    fontWeight: 'normal',
    alignItems: 'center',
    borderRadius: 2,
    borderWidth: 2,
    width: 150,
    fontFamily: 'vincHand',
    borderColor: '#CEDB56',
    backgroundColor: '#76cdd8',
  },
  text: {
    fontFamily: 'vincHand',
    fontSize: 25,
  },
  container: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  title: {
    fontFamily: 'vincHand',
    margin: 24,
    fontSize: 30,
    marginTop: 1,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  loginFieldText: {
    fontFamily: 'vincHand',
    margin: 24,
    fontSize: 25,
    marginTop: 1,
    textAlign: 'center',
    width: 300,
    backgroundColor: '#CCCCCC',
  },
  loginLogo: {
    fontFamily: 'vincHand',
    height: 50,
    width: 50,
  },
  view: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    height: 600,
  },
  productListContainer: {
    marginTop: 30,
    height: 300,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  productParagraph: {
    fontFamily: 'vincHand',
    fontSize: 15,
    height: 200,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  poductLogo: {
    fontFamily: 'vincHand',
    alignItems: 'flex-start',
    height: 15,
    width: 15,
  },
  rightContainer: {
    paddingLeft: 250,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  leftContainer: {
    paddingLeft: 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  productViewParagraph: {
    paddingLeft: 10,
    fontSize: 15,
    fontFamily: 'vincHand',
    flexDirection: 'row',
    fontWeight: 'normal',
    textAlign: 'center',
  },
  productViewLogo: {
    fontFamily: 'vincHand',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    height: 15,
    width: 15,
  },
    modalButton: {
    fontSize: 25,
    fontWeight: 'normal',
    textAlign: 'center',
    borderRadius: 2,
    borderWidth: 2,
    width: 100,
    marginTop: 20,
    marginLeft: 100,
    alignItems: 'center',
    fontFamily: 'vincHand',
    borderColor: '#CEDB56',
    backgroundColor: '#76cdd8',
  },
  modal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 30,
    marginRight: 30,
    width: 300,
    height: 300,
    textAlign: 'center',
  }
});
